logging:
  level:
    blog: WARN
    org: WARN
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASS:***REMOVED***}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mobileleDb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=TRUE
    username: ${MYSQL_USER:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    logging:
      level:

        org.hibernate.SQL:debug
        org.hibernate.type.descriptor.sql.BasicBinder:debug
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  sql:
#    init:
#      mode: never
mail:
  host: "localhost"
  port: 1025
  username: "ddf"
  password: " "

