logging:
  level:
    blog: WARN
    org: WARN
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ***REMOVED***
    url: jdbc:mysql://localhost:3306/mobileleDb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=TRUE
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

#  sql:
#    init:
#      mode: never
mail:
  host: "localhost"
  port: 1025
  username: "ddf"
  password: " "
