logging:
    level:
        blog: WARN
        org: WARN
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ***REMOVED***
        url: jdbc:mysql://localhost:3306/mobileleDb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=TRUE
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
